{% set name = "caf.toolkit" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/caf.toolkit-{{ version }}.tar.gz
  sha256: 59776ca53a3d6778f66d1eb42e2380cbca4097e20209cc14b9f08c31169c3d76

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools_scm
    - versioneer-518
    - pip
  run:
    - python >=3.9
    - numpy >=1.19.0, <1.25.0
    - pandas >=1.4.0
    - tqdm >=4.50.2
    - sparse >=0.13.0
    - numba >=0.56.4
    - pydantic >=1.10, <2.0.0
    - strictyaml >=1.6
    - psutil >=5.9.0

test:
  imports:
    - caf.toolkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Transport-for-the-North/caf.toolkit
  summary: A toolkit of transport planning and appraisal functionalities
  dev_url: https://github.com/Transport-for-the-North/caf.toolkit
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BenTaylor-TfN
    - isaac-tfn
