{% set name = "caf.toolkit" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/caf_toolkit-{{ version }}.tar.gz
  sha256: 88ba7e52f8004161ac92bc588de25ce32d0df9f647c5ce0345f6ab9eab44d675

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=64.0.0
    - versioningit
    - pip
  run:
    - python >=3.9
    - numpy >=1.19.0
    - pandas >=2.0.0
    - tqdm >=4.50.2
    - sparse >=0.13.0, <0.15.0  # Error with conda recognising latest version number 15/01/24
    - pydantic >=2.5.0
    - strictyaml >=1.6
    - psutil >=5.9.0

test:
  imports:
    - caf.toolkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Transport-for-the-North/caf.toolkit
  summary: A toolkit of transport planning and appraisal functionalities
  dev_url: https://github.com/Transport-for-the-North/caf.toolkit
  license: LicenseRef-TfN-License
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BenTaylor-TfN
    - isaac-tfn
