{% set name = "caf.toolkit" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/caf_toolkit-{{ version }}.tar.gz
  sha256: 31c4ca19bfec31305c938bb96de081d0a6a89f59eae0342f208beb01d5f68269

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0.0
    - versioningit
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.19.0
    - pandas >=2.0.0
    - tqdm >=4.50.2
    - sparse >=0.15.4
    - pydantic >=2.5.0
    - strictyaml >=1.6
    - psutil >=5.9.0

test:
  imports:
    - caf.toolkit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Transport-for-the-North/caf.toolkit
  summary: A toolkit of transport planning and appraisal functionalities
  dev_url: https://github.com/Transport-for-the-North/caf.toolkit
  license: LicenseRef-TfN-License
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MattBuckley-TfN
    - BenTaylor-TfN
    - isaac-tfn
