{% set name = "caf.toolkit" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/caf.toolkit-{{ version }}.tar.gz
  sha256: 31c4ca8af602bac73bda4f1caa7ecab26297cf7defc995a60bbd3ffbc7aa2e91

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=64.0.0
    - versioningit
    - pip
  run:
    - python >=3.9
    - numpy >=1.19.0, <1.25.0
    - pandas >=1.4.0, <2.0.0
    - tqdm >=4.50.2
    - sparse >=0.13.0
    - numba >=0.56.4
    - pydantic >=1.10, <2.0.0
    - strictyaml >=1.6, <2.0.0
    - psutil >=5.9.0

test:
  imports:
    - caf.toolkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Transport-for-the-North/caf.toolkit
  summary: A toolkit of transport planning and appraisal functionalities
  dev_url: https://github.com/Transport-for-the-North/caf.toolkit
  license: TfN-License
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BenTaylor-TfN
    - isaac-tfn
