{% set name = "caf.toolkit" %}
{% set version = "0.10.1" %}
package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/caf_toolkit-{{ version }}.tar.gz
  sha256: e46e5c67079a9a5fedc8332c7f12bedcb2add5c45d0929506abcf2f0e8f14996
build:
  entry_points:
    - caf.toolkit = caf.toolkit.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0.0
    - versioningit
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.19.0
    - pandas >=2.0.0
    - tqdm >=4.50.2
    - sparse >=0.15.4
    - pydantic >=2.5.0
    - strictyaml >=1.6
    - psutil >=5.9.0
    - openpyxl >=3.1.5

test:
  imports:
    - caf.toolkit
  commands:
    - pip check
    - caf.toolkit --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Transport-for-the-North/caf.toolkit
  summary: A toolkit of transport planning and appraisal functionalities
  dev_url: https://github.com/Transport-for-the-North/caf.toolkit
  license: LicenseRef-TfN-License
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MattBuckley-TfN
    - BenTaylor-TfN
    - isaac-tfn
